In [2]:
import torch
import torch.nn.functional as F

In [8]:
torch.__config__.show()

'PyTorch built with:\n  - GCC 13.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2024.2-Product Build 20240605 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v3.7.1 (Git Hash 8d263e693366ef8db40acc569cc7d8edf644556d)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 12.8\n  - NVCC architecture flags: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_100,code=sm_100;-gencode;arch=compute_120,code=sm_120\n  - CuDNN 91.0.2  (built against CUDA 12.9)\n    - Built with CuDNN 90.8\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, COMMIT_SHA=a1cb3cc05d46d198467bebbb6e8fba50a325d4e7, CUDA_VERSION=12.8, CUDNN_VERSION=9.8.0, CXX_COMPILER=/opt/rh/gcc-toolset-13/root/usr

In [21]:
a = torch.tensor(10)
b = torch.empty(10, 10)

In [26]:
b.element_size() * b.numel()

400

In [29]:
b.type?

Docstring:
type(dtype=None, non_blocking=False, **kwargs) -> str or Tensor
Returns the type if `dtype` is not provided, else casts this object to
the specified type.

If this is already of the correct type, no copy is performed and the
original object is returned.

Args:
    dtype (dtype or string): The desired type
    non_blocking (bool): If ``True``, and the source is in pinned memory
        and destination is on the GPU or vice versa, the copy is performed
        asynchronously with respect to the host. Otherwise, the argument
        has no effect.
    **kwargs: For compatibility, may contain the key ``async`` in place of
        the ``non_blocking`` argument. The ``async`` arg is deprecated.
Type:      builtin_function_or_method

In [30]:
help(b.type)

Help on built-in function type:

type(...) method of torch.Tensor instance
    type(dtype=None, non_blocking=False, **kwargs) -> str or Tensor
    Returns the type if `dtype` is not provided, else casts this object to
    the specified type.

    If this is already of the correct type, no copy is performed and the
    original object is returned.

    Args:
        dtype (dtype or string): The desired type
        non_blocking (bool): If ``True``, and the source is in pinned memory
            and destination is on the GPU or vice versa, the copy is performed
            asynchronously with respect to the host. Otherwise, the argument
            has no effect.
        **kwargs: For compatibility, may contain the key ``async`` in place of
            the ``non_blocking`` argument. The ``async`` arg is deprecated.



In [33]:
a = torch.zeros(10)
a[4] = 5
a

tensor([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [37]:
c = torch.arange(10, 50)

In [47]:
c.flip(dims=(0,))

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

In [48]:
d = torch.arange(0, 9)
d.reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [53]:
e = torch.Tensor([1, 2, 0, 0, 4, 0])
e.nonzero()
e[torch.where(e != 0)]

tensor([1., 2., 4.])

In [55]:
g = torch.eye(3, 3)
g

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [57]:
h = torch.rand((3, 3, 3))
h

tensor([[[0.1880, 0.7291, 0.1480],
         [0.0337, 0.8824, 0.7636],
         [0.9427, 0.0937, 0.6616]],

        [[0.9745, 0.6783, 0.2968],
         [0.5463, 0.3661, 0.5105],
         [0.5013, 0.8476, 0.2884]],

        [[0.8204, 0.2839, 0.0791],
         [0.2231, 0.5875, 0.8494],
         [0.0665, 0.8692, 0.1858]]])

In [59]:
i = torch.rand((10, 10))
print(torch.max(i))
print(torch.min(i))

tensor(0.9969)
tensor(0.0220)


In [60]:
g = torch.rand((30))
print(torch.mean(g))

tensor(0.4648)


In [63]:
j = torch.ones((4, 4))
j[1:-1, 1:-1] = 0
j

tensor([[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]])

In [68]:
j = torch.ones((4, 4))
F.pad(j, [1, 1, 1, 1], value=0)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [75]:
torch.diag(torch.arange(1, 5), diagonal=-1)

tensor([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

In [80]:
k = torch.ones(8, 8)
k[::2, ::2] = 0
k[1::2, 1::2] = 0
k

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

In [3]:
l = torch.ones(6, 7, 8)
torch.unravel_index(torch.tensor(99), (6, 7, 8))

(tensor(1), tensor(5), tensor(3))

In [4]:
torch.tile?

Docstring:
tile(input, dims) -> Tensor

Constructs a tensor by repeating the elements of :attr:`input`.
The :attr:`dims` argument specifies the number of repetitions
in each dimension.

If :attr:`dims` specifies fewer dimensions than :attr:`input` has, then
ones are prepended to :attr:`dims` until all dimensions are specified.
For example, if :attr:`input` has shape (8, 6, 4, 2) and :attr:`dims`
is (2, 2), then :attr:`dims` is treated as (1, 1, 2, 2).

Analogously, if :attr:`input` has fewer dimensions than :attr:`dims`
specifies, then :attr:`input` is treated as if it were unsqueezed at
dimension zero until it has as many dimensions as :attr:`dims` specifies.
For example, if :attr:`input` has shape (4, 2) and :attr:`dims`
is (3, 3, 2, 2), then :attr:`input` is treated as if it had the
shape (1, 1, 4, 2).

.. note::

    This function is similar to NumPy's tile function.

Args:
    input (Tensor): the tensor whose elements to repeat.
    dims (tuple): the number of repetitions per dime

In [6]:
x = torch.tensor(([1, 0], [0, 1]))
torch.tile(x, [4, 4])

tensor([[1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1]])

In [14]:
m = torch.rand(5, 5)
m = (m - m.mean())/ m.std()
m

tensor([[ 1.7067,  1.3961,  0.2853, -0.2091, -1.5929],
        [-0.7665,  0.2416, -0.3494,  0.9371,  1.0084],
        [-1.0758, -0.6555,  0.8239,  0.1495,  0.5886],
        [-0.7237, -1.3557, -1.3324, -0.6594,  1.1173],
        [ 0.3279, -1.5726,  0.4797,  1.5613, -0.3304]])

In [15]:
a = torch.rand(5, 3) 
b = torch.ones(3, 2)
a @ b

tensor([[1.7784, 1.7784],
        [0.8589, 0.8589],
        [1.5929, 1.5929],
        [2.1366, 2.1366],
        [1.0127, 1.0127]])

In [19]:
torch.where?

Docstring:
where(condition, input, other, *, out=None) -> Tensor

Return a tensor of elements selected from either :attr:`input` or :attr:`other`, depending on :attr:`condition`.

The operation is defined as:

.. math::
    \text{out}_i = \begin{cases}
        \text{input}_i & \text{if } \text{condition}_i \\
        \text{other}_i & \text{otherwise} \\
    \end{cases}

.. note::
    The tensors :attr:`condition`, :attr:`input`, :attr:`other` must be :ref:`broadcastable <broadcasting-semantics>`.

Arguments:
    condition (BoolTensor): When True (nonzero), yield input, otherwise yield other
    input (Tensor or Scalar): value (if :attr:`input` is a scalar) or values selected at indices
                          where :attr:`condition` is ``True``
    other (Tensor or Scalar): value (if :attr:`other` is a scalar) or values selected at indices
                          where :attr:`condition` is ``False``

Keyword args:
    out (Tensor, optional): the output tensor.

Returns:
    Tensor:

In [26]:
c = torch.arange(0, 10)
c[(c>3) & (c<9)] *= -1
c

tensor([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])